### PR TITLE
Workaround for autocomplete e2e issue.

### LINKED ISSUE #419: Flakey e2e test
```
FAIL  src/e2e/autocomplete.test.ts (18.068 s)
  ● Browser - autocomplete and signature help tests › does not insert brackets for import completion

    Evaluation failed: Error: Unable to find role="option"
```

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Optimistically closes #419

### CODE REVIEW

File: src/e2e/app.ts [hunk 1]
```diff
@@ -685,7 +688,7 @@ export class App {
       },
       defaultWaitForOptions
     );
-    option.click();
+    await option.click();
```
Comment (microbit-matt-hillsdon) [inline src/e2e/app.ts:691]: This is a bug but not the cause of our issue as it's after the failure.

**Review by microbit-robert — APPROVED** [review]
